FROM alpine:3.18

# Setup apache and php
RUN apk --no-cache --update \
    add apache2 \
    apache2-ssl \
    curl 

RUN apk add php82-apache2 \
    php82-bcmath \
    php82-bz2 \
    php82-calendar \
    php82-common \
    php82-ctype \
    php82-curl \
    php82-dom \
    php82-gd \
    php82-iconv \
    php82-mbstring \
    php82-mysqli \
    php82-mysqlnd \
    php82-openssl \
    php82-pdo_mysql \
    php82-pdo_pgsql \
    php82-pdo_sqlite \
    php82-phar \
    php82-session \
    php82-xml \
    && mkdir /htdocs

EXPOSE 80 443

RUN apk add mc bash 

ADD docker-entrypoint-websrv.sh /
RUN chmod 777 docker-entrypoint-websrv.sh


RUN apk add --no-check-certificate --no-cache pcre-dev php82-pear  php82-dev build-base 
COPY certs/*crt /usr/local/share/ca-certificates 
RUN update-ca-certificates \
&& pecl82 install redis  \  
&& echo "extension=redis.so" > /etc/php82/conf.d/redis.ini



COPY htdocs/ /var/www/localhost/htdocs/
VOLUME [ "/var/www/localhost/htdocs" ]

COPY  scripts/ /var/www/localhost/scripts/
VOLUME [ "/var/www/localhost/scripts/" ]

COPY logs /var/www/localhost/logs/
VOLUME [ "/var/www/localhost/logs" ]

HEALTHCHECK CMD wget -q --no-cache --spider localhost

ENTRYPOINT ["/docker-entrypoint-websrv.sh"]