FROM mariadb:10.6

# Setup apache and php: 2024-03-08 : there is temporary error in maridb repos, causing erro in apt-get
RUN apt-get -y  update 
RUN apt-get -y  install mc bash

COPY initdb.d/*.sql /docker-entrypoint-initdb.d/ 
COPY initdb.d/*.sh  /docker-entrypoint-initdb.d/
RUN chmod 777 /docker-entrypoint-initdb.d/*.sh


