FROM alpine:3.18


# Setup apache and php
RUN apk --no-cache --update \
    add apache2 \
    apache2-ssl \
    curl 


RUN apk add php82-apache2 \
    php82-bcmath \
    php82-bz2 \
    php82-calendar \
    php82-common \
    php82-ctype \
    php82-curl \
    php82-dom \
    php82-gd \
    php82-iconv \
    php82-mbstring \
    php82-mysqli \
    php82-mysqlnd \
    php82-openssl \
    php82-pdo_mysql \
    php82-pdo_pgsql \
    php82-pdo_sqlite \
    php82-phar \
    php82-session \
    php82-xml \
    && mkdir /htdocs

EXPOSE 80 443

RUN apk add mc bash 

ADD docker-entrypoint-web.sh /
RUN chmod 777 docker-entrypoint-web.sh

HEALTHCHECK CMD wget -q --no-cache --spider localhost

COPY htdocs/ /var/www/localhost/htdocs/
VOLUME [ "/var/www/localhost/htdocs" ]

ENTRYPOINT ["/docker-entrypoint-web.sh"]